# Generated by Django 5.2.18 on 2026-10-07 07:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('SHAPEFILE', 'Zipped Shapefile'), ('KML', 'KML')], max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('crs', models.CharField(blank=True, max_length=64)),
                ('feature_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('layer', models.CharField(blank=True, max_length=255)),
                ('geometry_type', models.CharField(max_length=32)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('measurement_status', models.CharField(choices=[('MEASURED', 'Measured'), ('NOT_APPLICABLE', 'No measurement for this geometry type'), ('UNSUPPORTED', 'Geometry type not supported'), ('ERROR', 'Measurement failed')], max_length=16)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('perimeter_m', models.FloatField(blank=True, null=True)),
                ('projected_crs', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('geofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geofiles.geofile')),
            ],
            options={
                'ordering': ['geofile', 'index'],
                'constraints': [models.UniqueConstraint(fields=('geofile', 'index'), name='unique_feature_index_per_file')],
            },
        ),
    ]
