# Generated by Django 5.2.18 on 2026-10-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='geodesic_area_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='geodesic_length_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geofile',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='feature',
            name='projected_crs',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
